apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
        - name: app
          image: pratimaa/practice
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: practice
spec:
  selector:
    app: practice
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000