 kind: Service
 apiVersion: v1
 metadata:
  name: practice
  labels:
    name: practice
 spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: practice
  type: NodePort  
  
---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: practice
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: practice
#  template:
#    metadata:
#      labels:
#        app: practice
#    spec:
#      containers:
#        - name: app
#          image: pratimaa/practice
#          ports:
#            - containerPort: 8081
#          imagePullPolicy: Always
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: practice
spec:                
  selector:         
    matchLabels:
      app: practice
  replicas: 2        
  template:
    metadata:
      labels:        
        app: practice
    spec:
      containers:
        - name: app
          image: pratimaa/practice
          ports:
            - containerPort: 8081                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: practice
#spec:
#  selector:
#    app: practice
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 8081
#      nodePort: 31000